/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApprovalPendingQueue: typeof import('./src/components/reports/ApprovalPendingQueue.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/components/AppTopbar.vue')['default']
    AssetDetailPanel: typeof import('./src/components/assets/AssetDetailPanel.vue')['default']
    AssetHealthPanel: typeof import('./src/components/assets/AssetHealthPanel.vue')['default']
    AssetTree: typeof import('./src/components/assets/AssetTree.vue')['default']
    AssetTreeNode: typeof import('./src/components/assets/AssetTreeNode.vue')['default']
    AssignmentBoard: typeof import('./src/components/workorders/AssignmentBoard.vue')['default']
    AuditLogTable: typeof import('./src/components/administration/AuditLogTable.vue')['default']
    BomApprovalQueue: typeof import('./src/components/bom/BomApprovalQueue.vue')['default']
    BomEditor: typeof import('./src/components/bom/BomEditor.vue')['default']
    BomLineItemsTable: typeof import('./src/components/bom/BomLineItemsTable.vue')['default']
    BomProjectList: typeof import('./src/components/bom/BomProjectList.vue')['default']
    BomReconciliation: typeof import('./src/components/bom/BomReconciliation.vue')['default']
    ComponentReservationTracker: typeof import('./src/components/procurement/ComponentReservationTracker.vue')['default']
    GlobalSettingsForm: typeof import('./src/components/administration/GlobalSettingsForm.vue')['default']
    LaborLogLedger: typeof import('./src/components/workorders/LaborLogLedger.vue')['default']
    LocationAutocompleteInput: typeof import('./src/components/shared/LocationAutocompleteInput.vue')['default']
    LocationRegistry: typeof import('./src/components/assets/LocationRegistry.vue')['default']
    LocationTreeNode: typeof import('./src/components/assets/LocationTreeNode.vue')['default']
    ManagementDashboard: typeof import('./src/components/dashboards/ManagementDashboard.vue')['default']
    MaterialLoggingSection: typeof import('./src/components/workorders/MaterialLoggingSection.vue')['default']
    MttrTrendReport: typeof import('./src/components/reports/MttrTrendReport.vue')['default']
    PermissionMatrix: typeof import('./src/components/administration/PermissionMatrix.vue')['default']
    ProjectDetailPanel: typeof import('./src/components/projects/ProjectDetailPanel.vue')['default']
    ProjectList: typeof import('./src/components/projects/ProjectList.vue')['default']
    ProjectListItem: typeof import('./src/components/projects/ProjectListItem.vue')['default']
    ProjectsMap: typeof import('./src/components/projects/ProjectsMap.vue')['default']
    ProjectStatusTracker: typeof import('./src/components/projects/ProjectStatusTracker.vue')['default']
    PurchaseRequestQueue: typeof import('./src/components/procurement/PurchaseRequestQueue.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StockAvailabilityPanel: typeof import('./src/components/procurement/StockAvailabilityPanel.vue')['default']
    SupervisorDashboard: typeof import('./src/components/dashboards/SupervisorDashboard.vue')['default']
    SystemHealthPanel: typeof import('./src/components/administration/SystemHealthPanel.vue')['default']
    TcoDashboard: typeof import('./src/components/reports/TcoDashboard.vue')['default']
    TechnicianDashboard: typeof import('./src/components/dashboards/TechnicianDashboard.vue')['default']
    UserRoleManagement: typeof import('./src/components/administration/UserRoleManagement.vue')['default']
    VendorManagement: typeof import('./src/components/procurement/VendorManagement.vue')['default']
    VendorPoStatus: typeof import('./src/components/procurement/VendorPoStatus.vue')['default']
    WorkOrderDetailPanel: typeof import('./src/components/workorders/WorkOrderDetailPanel.vue')['default']
    WorkOrderFilters: typeof import('./src/components/workorders/WorkOrderFilters.vue')['default']
    WorkOrderListItem: typeof import('./src/components/workorders/WorkOrderListItem.vue')['default']
    WorkOrderQueue: typeof import('./src/components/workorders/WorkOrderQueue.vue')['default']
  }
}
